CREATE TABLE "CONDUIT" (
    "IMMATRICULATION" VARCHAR2(100 BYTE) NOT NULL,
    "EMAIL" VARCHAR2(100 BYTE) NOT NULL
);

CREATE TABLE "EMPRUNTE" (
    "EMAIL" VARCHAR2(100 BYTE) NOT NULL,
    "NUMERO_TRONCON" NUMBER(*, 0) NOT NULL,
    "IDTRAJET" NUMBER(*, 0) NOT NULL
);

CREATE TABLE "ENERGIE_PRIX" (
    "ENERGIE_UTILISE" VARCHAR2(100 BYTE) NOT NULL,
    "COUT_ENERGIE" FLOAT(126) NOT NULL,
    CHECK (
        Cout_energie > 0
        AND (
            (Energie_utilise = 'diesel')
            OR (Energie_utilise = 'essence')
            OR (Energie_utilise = 'hybride')
            OR(Energie_utilise = 'electrique')
        )
    )
);

CREATE TABLE "TRAJET" (
    "IDTRAJET" NUMBER(*, 0) NOT NULL,
    "PLACE_DEPART" NUMBER(22, 0) NOT NULL,
    "IMMATRICULATION" VARCHAR2(100 BYTE) NOT NULL,
    "EMAIL" VARCHAR2(100 BYTE) NOT NULL,
    "DATE_ARRIVEE" TIMESTAMP (6) NOT NULL,
    "DATE_DEPART" TIMESTAMP (6) NOT NULL,
    "DEBUT_TRAJET" NUMBER(*, 0),
    "FIN_TRAJET" NUMBER(*, 0),
    PRIMARY KEY ("IDTRAJET"),
    CONSTRAINT "CHECK_DATE" CHECK (DATE_DEPART < DATE_ARRIVEE)
);

CREATE TABLE "TRONCON" (
    "NUMERO_TRONCON" NUMBER(*, 0) NOT NULL,
    "IDTRAJET" NUMBER(*, 0) NOT NULL,
    "GPS_DEPART" VARCHAR2(100 BYTE) NOT NULL,
    "GPS_ARRIVEE" VARCHAR2(100 BYTE) NOT NULL,
    "VILLE_DEPART" VARCHAR2(100 BYTE) NOT NULL,
    "VILLE_ARRIVEE" VARCHAR2(100 BYTE) NOT NULL,
    "DISTANCE_PARCOURUE" NUMBER(*, 0) NOT NULL,
    "TEMPS_ESTIME" NUMBER(*, 0) NOT NULL,
    "TEMPS_ATTENTE_DEPART" NUMBER(*, 0) NOT NULL,
    "MONTEE_VALIDEE" NUMBER(*, 0),
    "DESCENTE_VALIDEE" NUMBER(*, 0),
    CHECK (
        Distance_parcourue >= 0
        AND Temps_estime >= 0
        AND Temps_attente_depart >= 0
    ),
    PRIMARY KEY ("IDTRAJET", "NUMERO_TRONCON")
);

CREATE TABLE "UTILISATEUR" (
    "EMAIL" VARCHAR2(100 BYTE) NOT NULL,
    "NOM" VARCHAR2(100 BYTE) NOT NULL,
    "PRENOM" VARCHAR2(100 BYTE) NOT NULL,
    "VILLE_DE_RESIDENCE" VARCHAR2(100 BYTE) NOT NULL,
    "MDP" VARCHAR2(100 BYTE) NOT NULL,
    "PORTE_MONNAIE" FLOAT(126),
    CHECK (Porte_monnaie >= 0),
    PRIMARY KEY ("EMAIL")
);

CREATE TABLE "VEHICULE" (
    "IMMATRICULATION" VARCHAR2(100 BYTE) NOT NULL,
    "MARQUE" VARCHAR2(100 BYTE) NOT NULL,
    "MODELE" VARCHAR2(100 BYTE) NOT NULL,
    "PUISSANCE_FISCALE" NUMBER(*, 0) NOT NULL,
    "PLACE_VEHICULE" NUMBER(*, 0) NOT NULL,
    "ENERGIE_UTILISE" VARCHAR2(100 BYTE) NOT NULL,
    PRIMARY KEY ("IMMATRICULATION"),
    CONSTRAINT "CHECK_ENERGIEPUISSANCE" CHECK (
        Puissance_fiscale > 0
        AND Place_vehicule > 0
        AND (
            (Energie_utilise = 'diesel')
            OR (Energie_utilise = 'essence')
            OR (Energie_utilise = 'hybride')
            OR (Energie_utilise = 'electrique')
        )
    )
);